default:
  # HTTP related settings
  REQUEST_READ_TIMEOUT: 10
  REQUEST_CONN_TIMEOUT: 10
  WS_TIMEOUT: 10
  WS_RECV_TIMEOUT: 15
  HTTP_PROXY: null

  LOGGING_LEVEL: WARNING

  PAIRS:
    fcoin:
      ws:
        - BTC_USDT
        

development:
  HTTP_PROXY: http://127.0.0.1:1087
  LOGGING_LEVEL: DEBUG

  PAIRS:
    fcoin:
      ws:
        - BTC_USDT

  