default:
  # HTTP related settings
  REQUEST_READ_TIMEOUT: 10
  REQUEST_CONN_TIMEOUT: 10
  WS_TIMEOUT: 10                  # WS连接超时
  WS_RECV_TIMEOUT: 10             # WS在指定时间(s)内没有接受到数据，则超时错误
  WS_HEARTBEAT: 10
  WS_RECONNECT_INTERVAL: 5        # WS连接中断时候重连的间隔时间
  WS_RETRY_ON_CONNECT_LOST: yes   # 是否在WS连接失败的时候重新连接

  LOGGING_LEVEL: WARNING
  ORDERBOOK_LEVEL: 25

  MONGO_DATABASE: 'exchange_data'
  MONGO_REPORT_DATABASE: 'report'
  MONGO_S3_SYNC_COLLECTION: 'new_s3_sync'
  MONGO_POOL_SIZE: 100
  MONGO_BATCH_OP_SIZE: 15

  S3_BUCKET: 'dquant2'
  S3_PRESIGN_URL_EXPIRE: 15552000     # 过期时间为半年

  # monitors related settings
  EXCHANGES:
    okex_spot:
      symbols: ['btc_usdt', 'eos_usdt', 'eth_usdt', 'etc_usdt', 'bch_usdt', 'ltc_usdt', 'okb_usdt',
                'ltc_btc', 'etc_btc', 'eos_btc', 'eth_btc', 'bch_btc', 'okb_btc',
                'ltc_eth', 'okb_eth', 'etc_eth', 'bch_eth', 'eos_eth',
                'eos_okb', 'etc_okb', 'ltc_okb', 'bch_okb']
    okex_future:
      symbols: ['eos', 'ltc', 'eth', 'etc', 'bch', 'xrp', 'eos', 'btg']

    binance:
      # bcc是bch
      symbols: ['btcusdt', 'ethusdt', 'eosusdt', 'bccusdt', 'etcusdt', 'ltcusdt', 'bnbusdt',
                'ethbtc', 'eosbtc', 'bccbtc', 'etcbtc', 'ltcbtc', 'bnbbtc',
                'eoseth', 'bcceth', 'etceth', 'ltceth', 'bnbeth',
                'eosbnb', 'bccbnb', 'etcbnb', 'ltcbnb']

    huobi:
      symbols: ['btcusdt', 'bchusdt', 'ethusdt', 'etcusdt', 'ltcusdt', 'eosusdt', 'htusdt',
                'bchbtc', 'ethbtc', 'etcbtc', 'ltcbtc', 'eosbtc', 'htbtc',
                'hteth',
                'eosht', 'etcht', 'bchht', 'ltcht']

    bitfinex:
      symbols: ['fUSD', 'fBTC', 'fEOS', 'fETH', 'fBCH', 'fETC', 'fLTC', 'fEUR', 'fJPY',
                'tBTCUSD', 'tETHUSD', 'tEOSUSD', 'tBCHUSD', 'tETCUSD', 'tLTCUSD',
                'tETHBTC', 'tBCHBTC', 'tETCBTC', 'tEOSBTC',
                'tEOSETH', 'tBCHETH',
                'tBTCEUR', 'tETHEUR', 'tEOSEUR',
                'tBTCJPY', 'tETHJPY', 'tEOSJPY',
                'tBTCGBP', 'tETHGBP', 'tEOSGBP']

    bitflyer:
      symbols: ['BTC_JPY', 'FX_BTC_JPY', 'ETH_BTC', 'BCH_BTC',
                'BTCJPY28SEP2018', 'BTCJPY17AUG2018', 'BTCJPY24AUG2018']

    bitmex:
      symbols: ['XBTUSD', 'ADAU18', 'BCHU18', 'EOSU18', 'ETHUSD', 'LTCU18',
                'TRXU18', 'XRPU18']

    hitbtc:
      symbols: ['BTCUSD', 'ETHUSD', 'BCHUSD', 'LTCUSD',
                'ETHBTC', 'BCHBTC', 'XRPBTC', 'XMRBTC', 'DASHBTC', 'ZECBTC', 'LTCBTC',
                'ZRXETH', 'ADXETH', 'DICEETH',
                'XRPEURS']
    poloniex:
      symbols: ['USDT_BTC', 'USDT_LTC', 'USDT_ETH', 'USDT_ETC', 'USDT_BCH', 'USDT_EOS',
                'BTC_LTC', 'BTC_ETH', 'BTC_ETC', 'BTC_BCH', 'BTC_EOS',
                'ETH_ETC', 'ETH_BCH', 'ETH_EOS']

    fcoin:
      symbols: ['btcusdt', 'ethusdt', 'bchusdt', 'ltcusdt', 'etcusdt', 'eosusdt', 'ftusdt',
                'ethbtc', 'bchbtc', 'ltcbtc', 'etcbtc', 'eosbtc', 'ftbtc',
                'etceth', 'ltceth', 'eoseth', 'fteth']

    cointiger:
      symbols: ['tchbitcny', 'btcbitcny', 'ethbitcny',
                'btcusdt', 'ethusdt', 'ltcusdt', 'etcusdt',
                'tchbtc', 'bchbtc', 'eosbtc', 'ethbtc', 'etcbtc', 'ltcbtc',
                'eoseth']

    bithumb:
      symbols: ['BTC', 'ETH', 'LTC', 'ETC', 'BCH', 'EOS']

    zb:
      symbols: ['zbqc', 'btcqc', 'bccqc', 'ltcqc', 'ethqc', 'etcqc', 'eosqc',
                'bcczb', 'ltczb', 'ethzb', 'etczb', 'eoszb',
                'zbusdt', 'btcusdt', 'bccusdt', 'ltcusdt', 'ethusdt', 'etcusdt', 'eosusdt',
                'zbbtc', 'bccbtc', 'ltcbtc', 'ethbtc', 'etcbtc', 'eosbtc']

#    kraken:
#      symbols: ['BCHXBT', 'EOSXBT', 'ETCXBT', 'ETHXBT', 'LTCXBT',
#                'XBTEUR', 'BCHEUR', 'EOSEUR', 'ETCEUR', 'LTCEUR', 'ETHEUR',
#                'XBTJPY', 'ETHJPY',
#                'XBTUSD', 'BCHUSD', 'EOSUSD', 'ETCUSD', 'LTCUSD', 'USDTUSD', 'ETHUSD',
#                'EOSETH', 'ETCETH']

    # lbank的接口会报400错误
#    lbank:
#      symbols: ['btc_usdt', 'eth_usdt', 'bch_usdt', 'ht_usdt', 'ten_usdt', 'bnb_usdt',
#                'eth_btc', 'bch_btc', 'ltc_btc', 'etc_btc',
#                'bch_eth', 'eos_eth',
#                'usdt_bu', 'eth_bu', 'btc_bu']

    # gateio的ws接口有一些问题，不是标准协议
#    gateio:
#      symbols: ['eos_usdt', 'eth_usdt', 'btc_usdt', 'etc_usdt', 'bch_usdt', 'ltc_usdt', 'qtum_usdt',
#                'eth_btc', 'eos_btc', 'bch_btc', 'etc_btc', 'ltc_btc', 'qtum_btc',
#                'eos_eth', 'etc_eth', 'qtum_btc']


development:
  LOGGING_LEVEL: WARNING

production:
  WS_TIMEOUT: 20                  # WS连接超时
  WS_RECV_TIMEOUT: 20             # WS在指定时间(s)内没有接受到数据，则超时错误
  WS_HEARTBEAT: 10
  WS_RECONNECT_INTERVAL: 2        # WS连接中断时候重连的间隔时间


  